media:
  input: src
  output: ../..
  path: src/assets
content:
  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    extension: mdoc
    fields:
      - name: body
        type: rich-text
        options:
          image:
            path: src/content/pages
  - name: notes
    label: Notes
    type: collection
    path: src/content/notes
    fields:
      - name: body
        type: rich-text
        options:
          image:
            path: src/content/notes
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    extension: mdoc
    fields:
      - name: body
        type: rich-text
        options:
          image:
            path: src/content/blog
