media:
  input: src/assets
  output: @assets
content:
  - name: pages
    label: Pages
    path: src/pages
    type: collection
    fields:
      - name: body
        type: rich-text
  - name: notes
    label: Notes
    path: src/content/notes
    type: collection
    fields:
      - name: body
        type: rich-text
