media:
  input: src
  output: ../..
  path: src/assets
content:
  - name: readme
    label: README
    type: file
    path: README.md
    fields:
      - name: body
        type: rich-text
  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    extension: mdoc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        type: rich-text
        options:
          image:
            path: src/content/pages
    view:
      default:
        order: asc
  - name: notes
    label: Notes
    type: collection
    path: src/content/notes
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        type: rich-text
        options:
          image:
            path: src/content/notes
    view:
      default:
        order: asc
  - name: publications
    label: Publications
    type: collection
    path: src/content/publications
    extension: mdoc
    fields:
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: image
        label: Image
        type: image
        list: true
        options:
#          path: src/content/publications
          categories: [image]
      - name: doc
        label: Document
        type: image
        list: true
        options:
#          path: src/content/publications
          categories: [document, video, audio, compressed]
      - name: body
        type: rich-text
        options:
          image:
            path: src/content/publications
    view:
      fields: [slug, date, title]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    extension: mdoc
    fields:
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        type: rich-text
        options:
          image:
            path: src/content/blog
    view:
      fields: [slug, date, title]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
