media:
  input: src
  output: ../..
  path: src/assets
content:
  - name: notes
    label: Notes
    type: collection
    path: src/content/notes
    fields:
      - name: body
        type: rich-text
  - name: blog
    label: Blog
    type: collection
    path: src/content/pages
    extension: mdoc
    fields:
      - name: body
        type: rich-text
        options:
          image:
            input: src
            output: ../../
            path: src/content/pages/{slug}
  - name: pages
    label: Pages
    path: src/pages
    type: collection
    fields:
      - name: layout
        type: string
        default: @layouts/Layout.astro
      - name: body
        type: rich-text
