name: Deploy
on:
  push:
    branches: rakkas
  pull_request:
    branches: rakkas

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0

      - name: Build step
        run: yarn build:pun # 📝 Update the build command(s)

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "pun-rakkas"
          entrypoint: "dist/deno/mod.js" # 📝 Update the entrypoint
          root: "."
